name: Node.js CI

on:
  # Trigger when a new pull request in main branch
  pull_request:
    branches:
      - main

jobs:
  checkout_code:
    name: Checkout Code
    uses: ./.github/workflows/checkout_code.yml@main
  setup_node:
    name: Installing Node.js
    uses: ./.github/workflows/setup_node.yml@main
  install_packages:
    name: Installing Node.js Packages
    uses: ./.github/workflows/install_packages.yml@main
  run_test:
    name: Run Test Case in Node.js Application
    uses: ./.github/workflows/run_test.yml@main
