name: Node.js CI

on:
  # Trigger when a new pull request in main branch
  pull_request:
    branches:
      - main

jobs:
  node_pipelines:
    runs-on: ubutu-latest
    steps:
      - name: Checkout Code
        uses: ./.github/workflows/checkout_code.yml
      
      - name: Installing Node.js
        uses: ./.github/workflows/setup_node.yml
      
      - name: Installing Node.js Packages
        uses: ./.github/workflows/install_packages.yml
      
      - name: Run Test Case in Node.js Application
        uses: ./.github/workflows/run_test.yml
